language: node_js # Node.js based project
node_js:
  - 13 
cache:
  directories:
  - node_modules 
script:
  - npm run build 
  - npm run export 
  - touch out/.nojekyll 
deploy:
  provider: pages 
  skip_cleanup: true 
  github_token: $github_token 
  local_dir: out 
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(master|main)$
